name: nucypher-contracts
contracts_folder: contracts

plugins:
  - name: solidity

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.1
  - name: openzeppelin-upgradeable
    github: OpenZeppelin/openzeppelin-contracts-upgradeable
    version: 4.8.1

solidity:
  version: 0.8.17
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.1"
    - "@openzeppelin-upgradeable/contracts=openzeppelin-upgradeable/v4.8.1"
